// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdAyR25MB0EROigXILjcxo9UyM82aFfs4',
    appId: '1:876825976672:web:05b9610a2abfc09cedc805',
    messagingSenderId: '876825976672',
    projectId: 'ruhsal-38a23',
    authDomain: 'ruhsal-38a23.firebaseapp.com',
    storageBucket: 'ruhsal-38a23.firebasestorage.app',
    measurementId: 'G-8X4TC4CPFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkOAJ3C03-pXxxnQ3iu5APPQSClmJNxk',
    appId: '1:876825976672:android:19536af256c2b0b9edc805',
    messagingSenderId: '876825976672',
    projectId: 'ruhsal-38a23',
    storageBucket: 'ruhsal-38a23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8EHVX642pDdgkWYIQLmYo5l7b8prcDF4',
    appId: '1:876825976672:ios:9c491ae915d70d0cedc805',
    messagingSenderId: '876825976672',
    projectId: 'ruhsal-38a23',
    storageBucket: 'ruhsal-38a23.firebasestorage.app',
    iosBundleId: 'com.example.ruhsalDurum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8EHVX642pDdgkWYIQLmYo5l7b8prcDF4',
    appId: '1:876825976672:ios:9c491ae915d70d0cedc805',
    messagingSenderId: '876825976672',
    projectId: 'ruhsal-38a23',
    storageBucket: 'ruhsal-38a23.firebasestorage.app',
    iosBundleId: 'com.example.ruhsalDurum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdAyR25MB0EROigXILjcxo9UyM82aFfs4',
    appId: '1:876825976672:web:4e2cab3f61262715edc805',
    messagingSenderId: '876825976672',
    projectId: 'ruhsal-38a23',
    authDomain: 'ruhsal-38a23.firebaseapp.com',
    storageBucket: 'ruhsal-38a23.firebasestorage.app',
    measurementId: 'G-YEVCKQT17X',
  );

}